/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author abida
 */
public class CalculatorOk extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorOk
     */
    //variable global
    double angka, jawaban;
    char simbol;
    public CalculatorOk() {
        initComponents();
        radioON.setEnabled(false);
        textHasil.setEditable(false);
    }
    private void operasi_aritmatika(){
        switch(simbol){
            case '+':
                jawaban = angka+Double.parseDouble(textHasil.getText());
                textHasil.setText(Double.toString(jawaban));
                break;
            case '-':
                jawaban = angka-Double.parseDouble(textHasil.getText());
                textHasil.setText(Double.toString(jawaban));
                break;
            case '*':
                jawaban = angka*Double.parseDouble(textHasil.getText());
                textHasil.setText(Double.toString(jawaban));
                break;
            case '/':
                jawaban = angka/Double.parseDouble(textHasil.getText());
                textHasil.setText(Double.toString(jawaban));
                break;
                
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelAtas = new javax.swing.JLabel();
        textHasil = new javax.swing.JTextField();
        radioON = new javax.swing.JRadioButton();
        radioOff = new javax.swing.JRadioButton();
        tombolDel = new javax.swing.JButton();
        tombolC = new javax.swing.JButton();
        tombolTambah = new javax.swing.JButton();
        tombol8 = new javax.swing.JButton();
        tombol9 = new javax.swing.JButton();
        tombolKurang = new javax.swing.JButton();
        tombol7 = new javax.swing.JButton();
        tombol5 = new javax.swing.JButton();
        tombol16 = new javax.swing.JButton();
        tombolKurangX = new javax.swing.JButton();
        tombol4 = new javax.swing.JButton();
        tombol3 = new javax.swing.JButton();
        tombolBagi = new javax.swing.JButton();
        tombol2 = new javax.swing.JButton();
        tombol1 = new javax.swing.JButton();
        tombolTitik = new javax.swing.JButton();
        tombolSamadengan = new javax.swing.JButton();
        tombol0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(700, 400));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        labelAtas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        buttonGroup1.add(radioON);
        radioON.setText("ON");
        radioON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioONActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioOff);
        radioOff.setText("OFF");
        radioOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOffActionPerformed(evt);
            }
        });

        tombolDel.setText("DEL");
        tombolDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolDelActionPerformed(evt);
            }
        });

        tombolC.setText("C");
        tombolC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCActionPerformed(evt);
            }
        });

        tombolTambah.setText("+");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombol8.setText("8");
        tombol8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol8ActionPerformed(evt);
            }
        });

        tombol9.setText("9");
        tombol9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol9ActionPerformed(evt);
            }
        });

        tombolKurang.setText("-");
        tombolKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKurangActionPerformed(evt);
            }
        });

        tombol7.setText("7");
        tombol7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol7ActionPerformed(evt);
            }
        });

        tombol5.setText("5");
        tombol5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol5ActionPerformed(evt);
            }
        });

        tombol16.setText("6");
        tombol16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol16ActionPerformed(evt);
            }
        });

        tombolKurangX.setText("x");
        tombolKurangX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKurangXActionPerformed(evt);
            }
        });

        tombol4.setText("4");
        tombol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol4ActionPerformed(evt);
            }
        });

        tombol3.setText("3");
        tombol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol3ActionPerformed(evt);
            }
        });

        tombolBagi.setText("/");
        tombolBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBagiActionPerformed(evt);
            }
        });

        tombol2.setText("2");
        tombol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol2ActionPerformed(evt);
            }
        });

        tombol1.setText("1");
        tombol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol1ActionPerformed(evt);
            }
        });

        tombolTitik.setText(".");
        tombolTitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTitikActionPerformed(evt);
            }
        });

        tombolSamadengan.setText("=");
        tombolSamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSamadenganActionPerformed(evt);
            }
        });

        tombol0.setText("0");
        tombol0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textHasil)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radioOff)
                                .addComponent(radioON)
                                .addComponent(tombol7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tombol4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tombol1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tombolTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tombolDel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tombol8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombol9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tombol5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombol16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolKurangX, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tombol2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombol3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tombol0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolSamadengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombolDel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombol8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombol5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolKurangX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombol2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombol1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombol0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolSamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioOff)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioONActionPerformed
        tombol1.setEnabled(true);
        tombol2.setEnabled(true);
        tombol3.setEnabled(true);
        tombol4.setEnabled(true);
        tombol5.setEnabled(true);
        tombol16.setEnabled(true);
        tombol7.setEnabled(true);
        tombol8.setEnabled(true);
        tombol9.setEnabled(true);
        tombol0.setEnabled(true);
        tombolTitik.setEnabled(true);
        tombolTambah.setEnabled(true);
        tombolKurang.setEnabled(true);
        tombolKurangX.setEnabled(true);
        tombolBagi.setEnabled(true);
        tombolSamadengan.setEnabled(true);
        tombolDel.setEnabled(true);
        tombolC.setEnabled(true);
        textHasil.setEnabled(true);
        radioOff.setEnabled(true);
        
    }//GEN-LAST:event_radioONActionPerformed

    private void tombolCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCActionPerformed
        // TODO add your handling code here:
        textHasil.setText("");
    }//GEN-LAST:event_tombolCActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        // textHasil.setText(textHasil.getText()+"+");
         angka = Double.parseDouble(textHasil.getText());
         simbol = '+';
         textHasil.setText("");
         labelAtas.setText(angka + "+");
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tombol9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol9ActionPerformed
         textHasil.setText(textHasil.getText()+"9");
    }//GEN-LAST:event_tombol9ActionPerformed

    private void tombolKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKurangActionPerformed
        // textHasil.setText(textHasil.getText()+"-");
         angka = Double.parseDouble(textHasil.getText());
         simbol = '-';
         textHasil.setText("");
         labelAtas.setText(angka + "-");
    }//GEN-LAST:event_tombolKurangActionPerformed

    private void tombol16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol16ActionPerformed
         textHasil.setText(textHasil.getText()+"6");
    }//GEN-LAST:event_tombol16ActionPerformed

    private void tombolKurangXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKurangXActionPerformed
       //  textHasil.setText(textHasil.getText()+"x");
       angka = Double.parseDouble(textHasil.getText());
       simbol = '*';
       textHasil.setText("");
       labelAtas.setText(angka + "x");
    }//GEN-LAST:event_tombolKurangXActionPerformed

    private void tombol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol3ActionPerformed
         textHasil.setText(textHasil.getText()+"3");
    }//GEN-LAST:event_tombol3ActionPerformed

    private void tombolBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBagiActionPerformed
//         textHasil.setText(textHasil.getText()+"/");
        angka = Double.parseDouble(textHasil.getText());
         simbol = '/';
         textHasil.setText("");
         labelAtas.setText(angka + "/");
    }//GEN-LAST:event_tombolBagiActionPerformed

    private void tombol5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol5ActionPerformed
         textHasil.setText(textHasil.getText()+"5");
    }//GEN-LAST:event_tombol5ActionPerformed

    private void tombol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol2ActionPerformed
         textHasil.setText(textHasil.getText()+"2");
    }//GEN-LAST:event_tombol2ActionPerformed

    private void tombolSamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSamadenganActionPerformed
        // TODO add your handling code here:
        operasi_aritmatika();
        labelAtas.setText("");
    }//GEN-LAST:event_tombolSamadenganActionPerformed

    private void tombol0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol0ActionPerformed
         textHasil.setText(textHasil.getText()+"0");
    }//GEN-LAST:event_tombol0ActionPerformed

    private void tombolDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolDelActionPerformed
        // TODO add your handling code here:
        int length =textHasil.getText().length(); 
        int number = textHasil.getText().length()-1;
        String store;
        if(length>0){
            StringBuilder back = new StringBuilder(textHasil.getText());
            back.deleteCharAt(number);
            store = back.toString();
            textHasil.setText(store);
        }
    }//GEN-LAST:event_tombolDelActionPerformed

    private void tombol7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol7ActionPerformed
        textHasil.setText(textHasil.getText()+"7");
    }//GEN-LAST:event_tombol7ActionPerformed

    private void tombol8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol8ActionPerformed
         textHasil.setText(textHasil.getText()+"8");
    }//GEN-LAST:event_tombol8ActionPerformed

    private void tombol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol4ActionPerformed
         textHasil.setText(textHasil.getText()+"4");
    }//GEN-LAST:event_tombol4ActionPerformed

    private void tombol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol1ActionPerformed
         textHasil.setText(textHasil.getText()+"1");
    }//GEN-LAST:event_tombol1ActionPerformed

    private void radioOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOffActionPerformed
         tombol1.setEnabled(false);
        tombol2.setEnabled(false);
        tombol3.setEnabled(false);
        tombol4.setEnabled(false);
        tombol5.setEnabled(false);
        tombol16.setEnabled(false);
        tombol7.setEnabled(false);
        tombol8.setEnabled(false);
        tombol9.setEnabled(false);
        tombol0.setEnabled(false);
        tombolTitik.setEnabled(false);
        tombolTambah.setEnabled(false);
        tombolKurang.setEnabled(false);
        tombolKurangX.setEnabled(false);
        tombolBagi.setEnabled(false);
        tombolSamadengan.setEnabled(false);
        tombolDel.setEnabled(false);
        tombolC.setEnabled(false);
        textHasil.setEnabled(false);
        radioON.setEnabled(true);
    }//GEN-LAST:event_radioOffActionPerformed

    private void tombolTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTitikActionPerformed
        textHasil.setText(textHasil.getText()+".");
    }//GEN-LAST:event_tombolTitikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorOk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel labelAtas;
    private javax.swing.JRadioButton radioON;
    private javax.swing.JRadioButton radioOff;
    private javax.swing.JTextField textHasil;
    private javax.swing.JButton tombol0;
    private javax.swing.JButton tombol1;
    private javax.swing.JButton tombol16;
    private javax.swing.JButton tombol2;
    private javax.swing.JButton tombol3;
    private javax.swing.JButton tombol4;
    private javax.swing.JButton tombol5;
    private javax.swing.JButton tombol7;
    private javax.swing.JButton tombol8;
    private javax.swing.JButton tombol9;
    private javax.swing.JButton tombolBagi;
    private javax.swing.JButton tombolC;
    private javax.swing.JButton tombolDel;
    private javax.swing.JButton tombolKurang;
    private javax.swing.JButton tombolKurangX;
    private javax.swing.JButton tombolSamadengan;
    private javax.swing.JButton tombolTambah;
    private javax.swing.JButton tombolTitik;
    // End of variables declaration//GEN-END:variables
}
